name = "fermyon-developer"
spin_version = "1"
version = "0.1.0"
description = "The Fermyon Developer website running on... Spin."
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]
trigger = { type = "http", base = "/" }

[[component]]
id = "bartholomew"
files = [ "content/**/*" , "templates/*", "scripts/*", "config/*", "shortcodes/*"]
[component.source]
url = "https://github.com/fermyon/bartholomew/releases/download/v0.6.0/bartholomew.wasm"
digest = "sha256:b64bc17da4484ff7fee619ba543f077be69b3a1f037506e0eeee1fb020d42786"
[component.trigger]
route = "/..."

[[component]]
id = "fileserver_static"
files = [ { source = "static/", destination = "/" } ]
[component.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm"
digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375"
[component.trigger]
route = "/static/..."

[[component]]
id = "fileserver_downloads"
files = [ { source = "downloads/", destination = "/" } ]
[component.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm"
digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375"
[component.trigger]
route = "/downloads/..."

# Redirect /spin to /spin/index
[[component]]
id = "redirect-spin-index"
environment = { DESTINATION = "/spin/index" }
[component.source]
url = "https://github.com/fermyon/spin-redirect/releases/download/v0.0.1/redirect.wasm"
digest = "sha256:d57c3d91e9b62a6b628516c6d11daf6681e1ca2355251a3672074cddefd7f391"
[component.trigger]
route = "/spin"
executor = { type = "wagi" }

# Redirect /cloud to /cloud/index
[[component]]
id = "redirect-cloud-index"
environment = { DESTINATION = "/cloud/index" }
[component.source]
url = "https://github.com/fermyon/spin-redirect/releases/download/v0.0.1/redirect.wasm"
digest = "sha256:d57c3d91e9b62a6b628516c6d11daf6681e1ca2355251a3672074cddefd7f391"
[component.trigger]
route = "/cloud"
executor = { type = "wagi" }

# Redirect /bartholomew to /bartholomew/index
[[component]]
id = "redirect-bartholomew-index"
environment = { DESTINATION = "/bartholomew/index" }
[component.source]
url = "https://github.com/fermyon/spin-redirect/releases/download/v0.0.1/redirect.wasm"
digest = "sha256:d57c3d91e9b62a6b628516c6d11daf6681e1ca2355251a3672074cddefd7f391"
[component.trigger]
route = "/bartholomew"
executor = { type = "wagi" }

